version: '3.1'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: TLCRoomBookingDB
      MYSQL_USER: root
      MYSQL_PASSWORD: manoj2603
      MYSQL_ROOT_PASSWORD: manoj2603
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
